[Gssoc'21] Fixed the Bug in front-end
sruti2024/PRO_Act pull request #111
Opened 2021-04-06 12:46 UTC by arpit456jain

# Description:
There was a bug in front-end on add project page
the footer overlap the techstack and its looks very ugly and annoying.
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/55352601/113712684-0dac6f80-9704-11eb-96f4-3a66e9e4ee2b.png">

Fixes #104 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

# Screenshots / Video:
<img width="960" alt="sol" src="https://user-images.githubusercontent.com/55352601/113712780-2c126b00-9704-11eb-959e-a88ca948f2eb.png">

2021-04-06 19:43 UTC, arpit456jain commented
@sruti2024 kindly add labels of GSSoC'21 and level before merging

2021-04-09 17:03 UTC, PROTechThor requested changes
Hi,

The output looks good. There's a merge conflict here. Plus, I'm not comfortable with putting styles in HTML. Can you move it to the CSS file instead?

2021-04-09 17:03 UTC, PROTechThor commented on templates/project_add.html
> +      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="z-index:100000">
Why are you adding the style to HTML, instead of using CSS. It's no a big deal, but I believe keeping all styles in the CSS file is a good practice.

2021-04-09 17:42 UTC, arpit456jain commented
> Hi,
> 
> The output looks good. There's a merge conflict here. Plus, I'm not comfortable with putting styles in HTML. Can you move it to the CSS file instead?

Yeah sure give me just 1 min

2021-04-09 17:49 UTC, arpit456jain commented
@PROTechThor kindly add labels of GSSoC'21 and level

2021-04-09 18:02 UTC, arpit456jain commented
@PROTechThor I had resolved the conflicts .

2021-04-10 19:02 UTC, arpit456jain commented
@PROTechThor @sruti2024 kindly merge this PR and add labels before merging its a very small level 1 bug.

2021-04-11 20:03 UTC, arpit456jain commented
@PROTechThor @SaiSudhaV @sruti2024 kindly review this PR

2021-04-13 16:09 UTC, arpit456jain commented
@PROTechThor kindly approve PR and add labels to it

2021-04-15 05:31 UTC, closed without merging