Update README.md
sruti2024/PRO_Act pull request #183
Opened 2021-05-03 17:29 UTC by KajalSinghBAGHEL

remove grammatical mistake

2021-05-03 17:30 UTC, KajalSinghBAGHEL commented
I am a GSSOC participant. Please check my pull request

2021-05-04 07:07 UTC, Aryamanz29 commented
Hii 👋  @KajalSinghBAGHEL 
Thanks for opening PR, but one thing I've noticed that PR doesn't follow the PR template  ( I mean, your PR should be descriptive). Another thing is that did you first open a new issue before raising this PR? I think it should be better if you first open an issue and then raise the PR 😅

2021-05-04 07:12 UTC, Aryamanz29 requested changes

2021-05-04 07:12 UTC, Aryamanz29 commented on README.md
> +    python manage.py run server
Please change this to `runserver` because it is a command & It won't work if it contains whitespace.

2021-05-04 16:38 UTC, sruti2024 commented
@Aryamanz29 I do appreciate for your comments as I too have a similar opinion , firstly working on grammatical mistakes and spelling mistakes are not eligible for any marking under gssoc'21 , If you wish to do it just for enhancement then u are heartily welcome !
please keep in mind not to randomly work out an issue if it is not assigned , here I suppose u have not even created one  and please don't change any command unless u have idea of them

2021-05-07 01:10 UTC, PROTechThor commented
> @Aryamanz29 I do appreciate for your comments as I too have a similar opinion , firstly working on grammatical mistakes and spelling mistakes are not eligible for any marking under gssoc'21 , If you wish to do it just for enhancement then u are heartily welcome !
> please keep in mind not to randomly work out an issue if it is not assigned , here I suppose u have not even created one and please don't change any command unless u have idea of them

@sruti2024 Eventhough this can't be accepted under GSSoC, can we merge it anyway? There are some good spelling fixes in there.

2021-05-20 15:29 UTC, closed without merging