Snake_case
sruti2024/PRO_Act pull request #194
Opened 2021-05-13 13:40 UTC by Srishti013

# Description:

I have changed the name of kebab-case files to snake_case.

Fixes # (issue no.) 
fixes[#165]
## Type of change:
- [ ] Bug fix (non-breaking change which fixes an issue)

 
# Checklist:
- [ ] My changes generate no new warnings.

2021-05-13 14:02 UTC, Aryamanz29 commented
Hii 👋 @Srishti013 
PR looks good, but you have to do some minors changes 📝
- Change PR title ( should be more descriptive)🎯
-  I think you may forget issue 4th point
     - **Note: Do changes in the codebase as well if they link into the project**. 
- Please change these rename file names in the codebase as well like in the `views.py render` function,` HTML` files link `JS files`, etc📜
- Also don't forget to add a working `GIF/Video` in the PR description so that we can verify that your work doesn't break any existing feature 🎞

2021-05-13 15:30 UTC, Aryamanz29 requested changes

2021-05-13 15:30 UTC, Aryamanz29 commented on templates/forgot_password.html
>    <script src="{% static 'js/reset-pwd.js' %}"></script>
Rename `js/reset-pwd.js`

2021-05-13 15:36 UTC, Aryamanz29 approved these changes

2021-05-13 15:39 UTC, Aryamanz29 commented
@Srishti013 Nice work 🎉
- Now squash your commits (combine all your commits into `one  single commit`) for ref :https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc
- Add GIF/Video in PR description.

2021-05-13 15:44 UTC, Srishti013 commented
Sure

2021-05-13 16:00 UTC, SaiSudhaV commented
> Hii 👋 @Srishti013
> PR looks good, but you have to do some minors changes 📝
> 
> * Change PR title ( should be more descriptive)🎯
> * I think you may forget issue 4th point👇
>   
>   * **Note: Do changes in the codebase as well if they link into the project**.
> * Please change these rename file names in the codebase as well like in the `views.py render` function,` HTML` files link `JS files`, etc📜
> * Also don't forget to add a working `GIF/Video` in the PR description so that we can verify that your work doesn't break any existing feature 🎞
> 
> @sruti2024 @SaiSudhaV What do you think?

Yeah you're right 
@Srishti013 Please do following things
 - add working demo video / GIF
 - Link the issue

2021-05-14 08:04 UTC, Srishti013 commented
> > Hii 👋 @Srishti013
> > PR looks good, but you have to do some minors changes 📝
> > 
> > * Change PR title ( should be more descriptive)🎯
> > * I think you may forget issue 4th point👇
> >   
> >   * **Note: Do changes in the codebase as well if they link into the project**.
> > * Please change these rename file names in the codebase as well like in the `views.py render` function,` HTML` files link `JS files`, etc📜
> > * Also don't forget to add a working `GIF/Video` in the PR description so that we can verify that your work doesn't break any existing feature 🎞
> > 
> > @sruti2024 @SaiSudhaV What do you think?
> 
> Yeah you're right
> @Srishti013 Please do following things
> 
> * add working demo video / GIF
> * Link the PR with the issue you're working on

done

2021-05-15 07:31 UTC, Aryamanz29 commented
> > > Hii 👋 @Srishti013
> > > PR looks good, but you have to do some minors changes 📝
> > > 
> > > * Change PR title ( should be more descriptive)🎯
> > > * I think you may forget issue 4th point👇
> > >   
> > >   * **Note: Do changes in the codebase as well if they link into the project**.
> > > * Please change these rename file names in the codebase as well like in the `views.py render` function,` HTML` files link `JS files`, etc📜
> > > * Also don't forget to add a working `GIF/Video` in the PR description so that we can verify that your work doesn't break any existing feature 🎞
> > > 
> > > @sruti2024 @SaiSudhaV What do you think?
> > 
> > 
> > Yeah you're right
> > @Srishti013 Please do following things
> > 
> > * add working demo video / GIF
> > * Link the PR with the issue you're working on
> 
> done

@Srishti013 Please squash your commits.

2021-05-18 19:34 UTC, merged